name: Reusable Release Icon Pack

on:
  workflow_call:
    inputs:
      base_tag:
        required: true
        type: string
      icon_pack_name:
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  build_and_release:
    runs-on: self-hosted
    container:
      image: python:3.12-slim
      options: --user root

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl git zip
          rm -rf /var/lib/apt/lists/*

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Install uv tool
        run: uv pip install --system -e .

      - name: Run renderer for ${{ inputs.icon_pack_name }}
        run: python -m render "${{ inputs.icon_pack_name }}"

      - name: Create new tag
        run: |
          git config --global --add safe.directory $PWD
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          new_tag="${{ inputs.base_tag }}-${{ inputs.icon_pack_name }}"
          git tag -a "$new_tag" -m "Release $new_tag"
          git push origin "$new_tag"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_URL: https://github.com/${{ github.repository }}/releases/download/${{ inputs.base_tag }}-${{ inputs.icon_pack_name }}
        with:
          tag_name: "${{ inputs.base_tag }}-${{ inputs.icon_pack_name }}"
          name: "${{ inputs.icon_pack_name }} ${{ inputs.base_tag }}"
          body: |
            ### ðŸŽ¨ Icon Pack Variants

            <table>
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.white.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.deep-blue.SDICON">Stream Dock</a>
                </td>
              </tr>
            
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.emerald-green.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.warm-amber.SDICON">Stream Dock</a>
                </td>
              </tr>
            
              <tr>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.crimson-red.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple-transparent.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple-transparent.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple-transparent.SDICON">Stream Dock</a>
                </td>
                <td>
                  <img src="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple.thumb_16x9.png"><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple.streamDeckIconPack">Stream Deck</a><br/>
                  <a href="${{ env.RELEASE_URL }}/${{ inputs.icon_pack_name }}.royal-purple.SDICON">Stream Dock</a>
                </td>
              </tr>
            </table>
          files: |
            build/*.streamDeckIconPack
            build/*.SDICON
            build/*.thumb_16x9.png
