name: Release All Icon Packs

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  release-brands:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: brands

  release-chisel-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: chisel-regular

  release-classic-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-solid

  release-classic-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-regular

  release-classic-light:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-light

  release-classic-thin:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-thin

  release-duotone-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-solid

  release-duotone-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-regular

  release-duotone-light:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-light

  release-duotone-thin:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-thin

  release-etch-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: etch-solid

  release-jelly-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-regular

  release-jelly-duo-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-duo-regular

  release-jelly-fill-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-fill-regular

  release-notdog-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: notdog-solid

  release-notdog-duo-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: notdog-duo-solid

  release-sharp-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-solid

  release-sharp-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-regular

  release-sharp-light:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-light

  release-sharp-thin:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-thin

  release-sharp-duotone-solid:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-solid

  release-sharp-duotone-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-regular

  release-sharp-duotone-light:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-light

  release-sharp-duotone-thin:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-thin

  release-slab-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: slab-regular

  release-slab-press-regular:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: slab-press-regular

  release-thumbprint-light:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: thumbprint-light

  release-utility-semibold:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-semibold

  release-utility-duo-semibold:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-duo-semibold

  release-utility-fill-semibold:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-fill-semibold

  release-whiteboard-semibold:
    uses: render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: whiteboard-semibold
