name: Release All Icon Packs

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  release-brands:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: brands

  release-chisel-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: chisel-regular

  release-classic-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-solid

  release-classic-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-regular

  release-classic-light:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-light

  release-classic-thin:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: classic-thin

  release-duotone-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-solid

  release-duotone-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-regular

  release-duotone-light:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-light

  release-duotone-thin:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: duotone-thin

  release-etch-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: etch-solid

  release-jelly-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-regular

  release-jelly-duo-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-duo-regular

  release-jelly-fill-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: jelly-fill-regular

  release-notdog-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: notdog-solid

  release-notdog-duo-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: notdog-duo-solid

  release-sharp-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-solid

  release-sharp-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-regular

  release-sharp-light:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-light

  release-sharp-thin:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-thin

  release-sharp-duotone-solid:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-solid

  release-sharp-duotone-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-regular

  release-sharp-duotone-light:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-light

  release-sharp-duotone-thin:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: sharp-duotone-thin

  release-slab-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: slab-regular

  release-slab-press-regular:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: slab-press-regular

  release-thumbprint-light:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: thumbprint-light

  release-utility-semibold:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-semibold

  release-utility-duo-semibold:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-duo-semibold

  release-utility-fill-semibold:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: utility-fill-semibold

  release-whiteboard-semibold:
    uses: ./.github/workflows/render-icon-pack.yml
    with:
      base_tag: ${{ github.ref_name }}
      icon_pack_name: whiteboard-semibold

  release-all:
    runs-on: self-hosted
    needs:
      - release-brands
      - release-chisel-regular
      - release-classic-solid
      - release-classic-regular
      - release-classic-light
      - release-classic-thin
      - release-duotone-solid
      - release-duotone-regular
      - release-duotone-light
      - release-duotone-thin
      - release-etch-solid
      - release-jelly-regular
      - release-jelly-duo-regular
      - release-jelly-fill-regular
      - release-notdog-solid
      - release-notdog-duo-solid
      - release-sharp-solid
      - release-sharp-regular
      - release-sharp-light
      - release-sharp-thin
      - release-sharp-duotone-solid
      - release-sharp-duotone-regular
      - release-sharp-duotone-light
      - release-sharp-duotone-thin
      - release-slab-regular
      - release-slab-press-regular
      - release-thumbprint-light
      - release-utility-semibold
      - release-utility-duo-semibold
      - release-utility-fill-semibold
      - release-whiteboard-semibold
    steps:
      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Icon Packs ${{ github.ref_name }}"
          body: |
            ### ðŸŽ¨ Icon Packs
    
            <ul>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-brands">Brands ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-chisel-regular">Chisel Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-classic-solid">Classic Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-classic-regular">Classic Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-classic-light">Classic Light ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-classic-thin">Classic Thin ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-duotone-solid">Duotone Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-duotone-regular">Duotone Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-duotone-light">Duotone Light ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-duotone-thin">Duotone Thin ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-etch-solid">Etch Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-jelly-regular">Jelly Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-jelly-duo-regular">Jelly Duo Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-jelly-fill-regular">Jelly Fill Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-notdog-solid">Notdog Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-notdog-duo-solid">Notdog Duo Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-solid">Sharp Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-regular">Sharp Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-light">Sharp Light ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-thin">Sharp Thin ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-duotone-solid">Sharp Duotone Solid ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-duotone-regular">Sharp Duotone Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-duotone-light">Sharp Duotone Light ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-sharp-duotone-thin">Sharp Duotone Thin ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-slab-regular">Slab Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-slab-press-regular">Slab Press Regular ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-thumbprint-light">Thumbprint Light ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-utility-semibold">Utility Semibold ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-utility-duo-semibold">Utility Duo Semibold ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-utility-fill-semibold">Utility Fill Semibold ${{ github.ref_name }}</a></li>
              <li><a href="https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}-whiteboard-semibold">Whiteboard Semibold ${{ github.ref_name }}</a></li>
            </ul>
          make_latest: true
